# example values

indexing-settings:
  sites:
#    - url: https://lenta.ru
#      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: http://www.playback.ru
      name: PlayBack.Ru
#    - url: https://dombulgakova.ru
#      name: Дом Булгакова
#    - url: https://ipfran.ru
#      name: ИПФ РАН
#    - url: https://dimonvideo.ru
#      name: DimonVideo - программы | игры | фильмы | книги » Страница 1
#    - url: https://nikoartgallery.com
#      name: Галерея искусств Niko
    - url: https://et-cetera.ru
      name: Театр «Et Cetera»
#    - url: https://www.lutherancathedral.ru
#      name: Собор Петра и Павла - Собор Петра и Павла
#    - url: https://www.svetlovka.ru
#      name: Центральная городская молодежная библиотека им. М. А. Светлова




server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true










